name: Stock Checker

on:
    schedule:
        - cron: "*/6 * * * *" # runs every 6 minutes (UTC)
    workflow_dispatch: # manual trigger

jobs:
    check-stock:
        runs-on: ubuntu-latest
        steps:
            - name: Workflow started
              run: echo "GitHub Action started at $(date -u)"

            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Run stock checker
              run: node index.js
              env:
                  METHOD: ${{ secrets.METHOD }}
                  MAX_BODY_LENGTH: ${{ secrets.MAX_BODY_LENGTH }}
                  URL: ${{ secrets.URL }}
                  ACCEPT: ${{ secrets.ACCEPT }}
                  ACCEPT_LANGUAGE: ${{ secrets.ACCEPT_LANGUAGE }}
                  BASE_URL: ${{ secrets.BASE_URL }}
                  FRONTEND: ${{ secrets.FRONTEND }}
                  PRIORITY: ${{ secrets.PRIORITY }}
                  REFERER: ${{ secrets.REFERER }}
                  SEC_CH_UA: ${{ secrets.SEC_CH_UA }}
                  SEC_CH_UA_MOBILE: ${{ secrets.SEC_CH_UA_MOBILE }}
                  SEC_CH_UA_PLATFORM: ${{ secrets.SEC_CH_UA_PLATFORM }}
                  SEC_FETCH_DEST: ${{ secrets.SEC_FETCH_DEST }}
                  SEC_FETCH_MODE: ${{ secrets.SEC_FETCH_MODE }}
                  SEC_FETCH_SITE: ${{ secrets.SEC_FETCH_SITE }}
                  TID: ${{ secrets.TID }}
                  USER_AGENT: ${{ secrets.USER_AGENT }}
                  COOKIE: ${{ secrets.COOKIE }}
                  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
                  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
                  TELEGRAM_URL: ${{secrets.TELEGRAM_URL}}

            - name: Workflow finished
              run: echo "GitHub Action finished at $(date -u)"
